### ISSUE TITLE
Gem package

### ISSUE THREAD

**Issue by lzap** [evan/has_many_polymorphs#19]
Hello,

I am going to create a package for Fedora. Do you have plans to release a gem?

Would be nice. Its easier and more efficient for linux distribution to track gem releases and then repack them.

**Comment by evan** [comment]
no plans for anything, I'm not maintaining this library anymore.

**Comment by lzap** [comment]
Okay. Thanks. Please close then.

http://koji.fedoraproject.org/koji/taskinfo?taskID=2761803
