### ISSUE TITLE
Error with the plugin...

### ISSUE THREAD

**Issue by meltzerj** [evan/has_many_polymorphs#20]
I get this error from the plugin when I try to create a new model:

/rubyprograms/dreamstill/vendor/plugins/has_many_polymorphs/lib/has_many_polymorphs/configuration.rb:7: Configuration is not a class (TypeError)
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in`require'
    from /rubyprograms/dreamstill/vendor/plugins/has_many_polymorphs/lib/has_many_polymorphs.rb:23
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in`require'
    from /rubyprograms/dreamstill/vendor/plugins/has_many_polymorphs/init.rb:2
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/plugin.rb:81
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `instance_exec'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/initializable.rb:25:in`run'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/initializable.rb:50:in `run_initializers'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/initializable.rb:49:in`each'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `run_initializers'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/application.rb:134:in`initialize!'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/application.rb:77:in `send'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/application.rb:77:in`method_missing'
    from /rubyprograms/dreamstill/config/environment.rb:5
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/application.rb:103:in `require'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/application.rb:103:in`require_environment!'
    from /Library/Ruby/Gems/1.8/gems/railties-3.0.4/lib/rails/commands.rb:16
    from script/rails:6:in `require'
    from script/rails:6

What's going on here?

**Comment by evan** [comment]
What Rails are you on? has_many_polymorphs is deprecated for Rails after about 2.2 or so, sorry.

**Comment by meltzerj** [comment]
Yeah... I'm on Rails 3, so that makes sense. I installed a number of forks by others that supposedly are Rails 3 compatible, although I always get this error: http://stackoverflow.com/questions/5773379/how-do-i-patch-this-error-that-has-many-polymorphs-plugin-is-giving-me

Not sure if it is due to Rails 3 incompatibility or if it's just something I'm doing. If the problem is not easily solvable, I'm thinking of just using a number of has_many through associations to accomplish the same thing. It's a shame because I find your plugin really useful.

Justin

**Comment by evan** [comment]
I guess try reporting the issue on whatever fork you are using. Good luck!
